// automatically generated by the FlatBuffers compiler, do not modify

package region

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BasicBoard struct {
	_tab flatbuffers.Table
}

func GetRootAsBasicBoard(buf []byte, offset flatbuffers.UOffsetT) *BasicBoard {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BasicBoard{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *BasicBoard) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BasicBoard) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BasicBoard) Guard(obj *GuardUnit) *GuardUnit {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(GuardUnit)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BasicBoard) Plane(obj *Plane) *Plane {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Plane)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BasicBoardStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BasicBoardAddGuard(builder *flatbuffers.Builder, guard flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(guard), 0)
}
func BasicBoardAddPlane(builder *flatbuffers.Builder, plane flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(plane), 0)
}
func BasicBoardEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
