// automatically generated by the FlatBuffers compiler, do not modify

package region

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Region struct {
	_tab flatbuffers.Table
}

func GetRootAsRegion(buf []byte, offset flatbuffers.UOffsetT) *Region {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Region{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Region) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Region) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Region) Planes(obj *Plane, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Region) PlanesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RegionStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RegionAddPlanes(builder *flatbuffers.Builder, planes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(planes), 0)
}
func RegionStartPlanesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RegionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
