// automatically generated by the FlatBuffers compiler, do not modify

package region

const (
	TileTypeEmpty   = 0
	TileTypeBarrier = 1
)

var EnumNamesTileType = map[int]string{
	TileTypeEmpty:   "Empty",
	TileTypeBarrier: "Barrier",
}
