// automatically generated by the FlatBuffers compiler, do not modify

package region

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Tile struct {
	_tab flatbuffers.Table
}

func GetRootAsTile(buf []byte, offset flatbuffers.UOffsetT) *Tile {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Tile{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Tile) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Tile) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Tile) TileType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Tile) MutateTileType(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func TileStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TileAddTileType(builder *flatbuffers.Builder, tileType int32) {
	builder.PrependInt32Slot(0, tileType, 0)
}
func TileEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
