// automatically generated by the FlatBuffers compiler, do not modify

package region

const (
	UnitNONE      = 0
	UnitGuardUnit = 1
)

var EnumNamesUnit = map[int]string{
	UnitNONE:      "NONE",
	UnitGuardUnit: "GuardUnit",
}
